### PR TITLE
Add git-annex pre-commit hook

### PR DESCRIPTION
**Pull request by poelzi**
Adds git-annex pre-commit hook which is required, when you want to use git-annex in a repository.
git-annex adds large file support and automatic sync to git

### CODE REVIEW

**Comment by domenkozar** [comment]
Could you remove the editor config?

**Comment by poelzi** [comment]
Having a .editorconfig helps getting the style correct in the first place without running through formatting. My IDE also shows intention as red if they are not correct.
It is a [standard](https://editorconfig.org/) supported by many editors. What harm does it do ?

**Comment by domenkozar** [comment]
This hook is failing on darwin, can you take a look?

**Comment by poelzi** [comment]
It seems that git-annex is broken on darwin. I created ticket on [git-annex.branchable.com](https://git-annex.branchable.com/bugs/test__58___posix__95__spawnp_broken_10_on_darwin)

**Pull request merged**
