### PR TITLE
Add ripsecrets hook

### PR DESCRIPTION
**Pull request by lafrenierejm**
<https://github.com/sirwart/ripsecrets> is the project's homepage.

### CODE REVIEW

**Comment by lafrenierejm** [comment]
I do not think the CI failure is due to this change.

> error: 1 dependencies of derivation '/nix/store/qjfc4daw3bmnlsv3nfalm80hj9229knb-git-annex-10.20230926.drv' failed to build

I receive a similar error in the same package (git-annex) when building `master`, 5df5a70ad7575f6601d91f0efec95dd9bc619431, locally.

**Comment by domenkozar** [comment]
Sorry for the mess, we revamed module structure in https://github.com/cachix/pre-commit-hooks.nix/pull/397, could you port these changes over?

**Comment by domenkozar** [comment]
seems like you need to run the hooks :)

**Comment by lafrenierejm** [comment]
> seems like you need to run the hooks :)

@domenkozar I have run the hooks. Apologies for the inconvenience; I'm not sure how I missed them before…

**Pull request merged**
