### PR TITLE
Add a hook for `headache`

### PR DESCRIPTION
**Pull request by Niols**
This PR adds a pre-commit hook for [headache](https://github.com/frama-c/headache), a “lightweight tool for managing headers in source code files.” `headache` was also added to nixpkgs quite recently, so I include a tiny hack similar to the one previously made for eg. `checkmake`.

My only worry for this PR is that the size of `headache`'s derivation is quite big. It isn't really a problem for OCaml projects that already rely on the same `nixpkgs`, but it is maybe a bit much for other projects.

### CODE REVIEW

**Comment by domenkozar** [comment]
What's the closure size? Also, there's a conflict from another PR.

**Comment by Niols** [comment]
I force-pushed [ed3d3d1](https://github.com/cachix/pre-commit-hooks.nix/pull/286/commits/ed3d3d1fc1febb4e9e9cf041cc7af01d8f2afbf0) to fix the conflict with `master`.

As for the closure, I am not sure how to measure it properly. The README suggests to do something such as:
```console
$ du -sh $(nix-build -A go)
463M	/nix/store/v4ys4lrjngf62lvvrdbs7r9kbxh9nqaa-go-1.18.6
```
but I am not sure where to do this. From the root of `pre-commit-hooks`, I get:
```console
$ du -sh $(nix-build -A headache)
1.8M	/nix/store/9i193xak8v19a7d0ql3jd5p81271yvii-ocaml4.14.1-headache-1.06
```
However, `headache` needs the full OCaml compiler and a bunch of libraries to compile correctly, so I suppose it should be much bigger? But maybe only 1.8M need to be downloaded if you use the Cachix instance?

**Comment by domenkozar** [comment]
`du -sh $(nix-store -qR $(nix-build -A headache))`

**Comment by Niols** [comment]
```
$ du -sh $(nix-store -qR $(nix-build -A headache))
152K	/nix/store/wv33zvn4m0j6qlipy5ybfrixgipnfnyj-xgcc-12.2.0-libgcc
1.8M	/nix/store/jrid72i6ii9wx2ia6fyr2b1plri2m07l-libunistring-1.1
612K	/nix/store/y382xj6bh8h4mmm22sw1a6q81rijrxl7-libidn2-2.3.4
31M	/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8
8.5M	/nix/store/9j1pfpw69j4lqh24gvwksfqnbs1q70ww-linux-headers-6.2
2.7M	/nix/store/v1nar35045dqwf8yy572yvbbcg2w2678-glibc-2.37-8-bin
3.4M	/nix/store/wb2dlc8kpvrn960vq7j7c8822pi43n48-glibc-2.37-8-dev
421M	/nix/store/46hyi2b6plki7x5x099hvaad8biwzpnx-ocaml-4.14.1
31M	/nix/store/8szmrj5z9manggbl9c2wa78hmg00x062-ocaml4.14.1-camomile-1.0.2
1.8M	/nix/store/9i193xak8v19a7d0ql3jd5p81271yvii-ocaml4.14.1-headache-1.06
```
Looks like we're around 500M here.

**Comment by domenkozar** [comment]
Is there any way to make it smaller?

**Comment by Niols** [comment]
What do you think of https://github.com/cachix/pre-commit-hooks.nix/pull/286/commits/31522e851a65b5bafe9292395d61e12a37c0597c? Now I get:
```console
$ du -sh $(nix-store -qR $(nix-build -A headache))
152K	/nix/store/wv33zvn4m0j6qlipy5ybfrixgipnfnyj-xgcc-12.2.0-libgcc
1.8M	/nix/store/jrid72i6ii9wx2ia6fyr2b1plri2m07l-libunistring-1.1
612K	/nix/store/y382xj6bh8h4mmm22sw1a6q81rijrxl7-libidn2-2.3.4
31M	/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8
1.7M	/nix/store/d8swmg2vqql3zw1f7vyxxsf8vlrpj7qm-headache-stripped
```
so about 35M including 31M of glibc.

**Comment by domenkozar** [comment]
Ideally stripped version of headache would live in nixpkgs, but this is a good start!

**Comment by Niols** [comment]
> Ideally stripped version of headache would live in nixpkgs.

Yes, agreed. I am currently discussing with people on how best to achieve that!

**Pull request merged**
