### PR TITLE
Add Support for `statix`

### PR DESCRIPTION
**Pull request by maydayv7**
Adds a `statix` hook for linting Nix expressions

Homepage: https://github.com/nerdypepper/statix

### CODE REVIEW

**Comment by maydayv7** [comment]
The `statix` package is not available in the `nixpkgs` version used by the project, so I'm not sure whether to bump the version by myself, or create a dummy package for it

**Comment by maydayv7** [comment]
CC @domenkozar

**Comment by domenkozar** [comment]
Could you rebase?

**Comment by maydayv7** [comment]
Is it fine now?

**Comment by maydayv7** [comment]
Updated to v0.5.4

**Pull request merged**
