### PR TITLE
Fixes #93

### LINKED ISSUE #93: Hpack does not seem to be able to deal with package.yaml files in subdirectories
```
hpack....................................................................Failed
- hook id: hpack
- exit code: 1

./package.yaml: Yaml file not found: /home/syd/src/sydtest/package.yaml
```

### PR DESCRIPTION
**Pull request by NorfairKing**
I tried it out on one of my projects with 
```
export NIV_OVERRIDE_nix_pre_commit_hooks=/home/syd/src/nix-pre-commit-hooks
```

CC @fiadliel

### CODE REVIEW

**Comment by NorfairKing** [comment]
I'm happy to take directions on the nix code here.
I used a new name: `hpack-dir` so that users can still add the `tools.hpack` to their shell and have it behave the way they think it will.

**Comment by domenkozar** [comment]
I'm not sure this is the correct fix. It's going against how pre-commit works by listing files on its own instead of getting it from pre-commit.

What is triggering #93?

cc @fiadliel

**Comment by NorfairKing** [comment]
@domenkozar I just followed the example of `terraform-fmt`. It also only lists files based on the arguments, which `pre-commit` passes in and will only be `package.yaml` files AFAICT.

**Comment by domenkozar** [comment]
I see, I've missed the `$@` bit :) Looks good to me, hoping @fiadliel can take a look before I merge it.

**Comment by domenkozar** [comment]
I've merged this, @fiadliel if you want to review it feel free to and we'll make the changes in a new PR.

**Pull request merged**
