### PR TITLE
Add purs-tidy checks

### PR DESCRIPTION
**Pull request by tfc**

### CODE REVIEW

**Comment by domenkozar** [comment]
Maybe now it's time to try bumping the channels again?

**Comment by tfc** [comment]
> Maybe now it's time to try bumping the channels again?

Just did.

**Comment by domenkozar** [comment]
See #181 for a rebase

**Comment by tfc** [comment]
@domenkozar rebased on #181

**Comment by domenkozar** [comment]
Oh, I need to bump flakes as well.

**Comment by domenkozar** [comment]
Alright, it's much harder than I thought: https://github.com/numtide/flake-utils/pull/82

**Comment by domenkozar** [comment]
Alright, hopefully it needs the last rebase :pray:

**Pull request merged**
