### PR TITLE
Add nix flakes support

### LINKED ISSUE #57: Expose as a flake
Currently its not possible to use this with `nix develop` because it internally re-imports nixpkgs:

```
error: --- EvalError --------------------------------------------------------------------------------- nix
at: (90:39) in file: /nix/store/ma3b77vjls3qrznwh66ix5ivvybx6003-source/pkgs/top-level/impure.nix

    89|                 else (if args ? localSystem then {}
    90|                       else { system = builtins.currentSystem; }) // localSystem;
      |                                       ^
    91| })

attribute 'currentSystem' missing
(use '--show-trace' to show detailed location information)
direnv: export +IN_NIX_SHELL ~PATH
```

### PR DESCRIPTION
**Pull request by Myhlamaeus**
This adds a `flake.nix` which exposes the project's outputs (mainly `packages.{system}.run`) and defines the dependencies.

`niv` was removed as nix flakes obviate it.

BREAKING CHANGES: The project.nix module is now exposed as an output
`projectModules.pre-commit-hooks` on the flake instead of a separate file.

Fixes #57

### CODE REVIEW

**Comment by Myhlamaeus** [comment]
I'll soon create a corresponding PR on hercules-ci/project.nix as this PR breaks compatibility with it.

**Comment by domenkozar** [comment]
This needs a rebase on top of master that landed 20.09 and other things :)

**Comment by Stupremee** [comment]
Is this planned to be merged any time soon?

**Comment by roberth** [comment]
We should only offer a cleaned-up interface in the flake. Otherwise people will have to migrate twice - once for flakes and then again for the revised interface. This means implementing some of the ideas in #55 and #61.
This also means we can get rid of some of the inputs and take them from Nixpkgs.
If you enjoy removing unnecessary wiring, I'd be happy to review. Otherwise I can do it, but probably no earlier than a month from now.

**Comment by Stupremee** [comment]
I don't think I have enough experience with Nix to do it.

**Comment by terlar** [comment]
Did this result in anything, I see nothing linked here, so I guess not, but just checking as this would be a nice feature to have.

**Comment by dhess** [comment]
Even just a simple fix for the `currentSystem` error when evaluating this project in a flake would be really helpful:

```
error: attribute 'currentSystem' missing

       at /nix/store/smvan4qznfgg79w1s6wjw1zdbszkynav-source/pkgs/top-level/impure.nix:90:39:

           89|                 else (if args ? localSystem then {}
           90|                       else { system = builtins.currentSystem; }) // localSystem;
             |                                       ^
           91| })
(use '--show-trace' to show detailed location information)
```

**Comment by domenkozar** [comment]
> Even just a simple fix for the `currentSystem` error when evaluating this project in a flake would be really helpful:
> 
> ```
> error: attribute 'currentSystem' missing
> 
>        at /nix/store/smvan4qznfgg79w1s6wjw1zdbszkynav-source/pkgs/top-level/impure.nix:90:39:
> 
>            89|                 else (if args ? localSystem then {}
>            90|                       else { system = builtins.currentSystem; }) // localSystem;
>              |                                       ^
>            91| })
> (use '--show-trace' to show detailed location information)
> ```

I'm happy to fix this - what's the easiest way to reproduce it?

**Comment by dhess** [comment]
@domenkozar Thanks for the offer! This public project has a `source-code-checks` attribute which builds fine using `nix-build` but not using `nix build` (with flakes support enabled):

https://github.com/hackworthltd/haskell-template/blob/a51b92252120a7fe82bc4d9f70842aae3526cbe8/flake.nix#L82

Beware that it uses `haskell.nix` so you'll probably want to be using the upstream `haskell.nix` binary cache. Alternatively, you could just take a look at what I'm doing there (it's pretty straightforward) and add it to a simple test flake.

BTW, I thought this was going to be a very easy fix as it looks like you just need to set `localSystem.system` to `system` in `nixpkgs`s args, but that still didn't work. If I recall, it has something to do with `niv`.

**Comment by domenkozar** [comment]
Sounds like the best way is to add flake support into the project itself.

I'm going to close this and track progress at https://github.com/cachix/pre-commit-hooks.nix/issues/57

**Comment by domenkozar** [comment]
Thanks @Myhlamaeus for your hard work, I've incorporated some of your changes and flake support is live now: https://github.com/cachix/pre-commit-hooks.nix#nix-flakes-support

**Pull request closed without merging**
