### PR TITLE
feat: add revive hook

### PR DESCRIPTION
**Pull request by roman**
Hello there :wave:,

As mentioned on a [different PR](https://github.com/cachix/pre-commit-hooks.nix/pull/177), I updated the `README.md` to include the newly added hooks. I also extended the example to include how to use `settings`, as I spent a meaningful amount of time trying to figure that out.

This PR includes a new hook for the `revive` linter, the replacement for `golint`.

Cheers.

### CODE REVIEW

**Comment by roman** [comment]
Uhmm, it seems we need to update `nixpkgs` to a newer revision to make this work. How often do you refresh `nixpkgs`?

**Comment by roman** [comment]
Ugh, it seems this is related to the branch we are using for `nixpkgs`, for some reason the `nixos-22.05` branch [does not have](https://github.com/NixOS/nixpkgs/tree/nixos-22.05/pkgs/development/tools) the changes for the `revive` tool; also the message `This branch is 3766 commits ahead, 40887 commits behind master.` makes me pause.

**Comment by domenkozar** [comment]
Need to update to master :)

**Comment by domenkozar** [comment]
See #181 for a rebase

**Comment by domenkozar** [comment]
Looks like you need to run pre-commit hooks :)

**Comment by roman** [comment]
> Looks like you need to run pre-commit hooks :)

You got me, I didn't want to install `lorri`, so I did an in-place modification to `flake.nix` to add a `devShells.default` entry. I'm guessing we don't want that in this repo, but in the off chance you are interested, I can create a PR with that.

Thanks.

**Pull request merged**
