### PR TITLE
fix: fix up tools indirections, ensure the used tools actually exist

### PR DESCRIPTION
**Pull request by K900**

### CODE REVIEW

**Comment by K900** [comment]
Fixes a bunch of hooks failing after #389

**Comment by domenkozar** [comment]
CI fails

**Comment by K900** [comment]
Well that's interesting. NixOS 23.05 did not have the attributes the hooks referred to, so now they don't evaluate. NixOS 23.11 has a different problem in that terraform is now unfree, so the hooks don't evaluate again.

**Comment by K900** [comment]
All right, I think it should be good now.

**Comment by K900** [comment]
Added a test to make sure this doesn't regress again. Unfortunately there's still the OSX build failure...

**Comment by domenkozar** [comment]
Great, let's fix this as a follow up :)

**Review by totoroot — COMMENTED** [review]
Thanks for this!

**Pull request merged**
